/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ComicStrip = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'slideId' : IDL.Text,
});

export const idlService = IDL.Service({
  'getComicStrips' : IDL.Func([], [IDL.Vec(ComicStrip)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ComicStrip = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'slideId' : IDL.Text,
  });
  
  return IDL.Service({
    'getComicStrips' : IDL.Func([], [IDL.Vec(ComicStrip)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };